### ISSUE TITLE
Task list for transition

### ISSUE THREAD

**Issue by osfameron** [mysociety/hassleme#17]
(Can be split out into multiple tickets)
# Immediate
- [x] PR https://github.com/mysociety/hassleme/pull/16 and deploy
- [x] run bin/export-users-and-tc-tokens to generate CSV for mailing list
- [x] send out emails to users (#12)
# after 1 week ("9th March" or later, depending on above)
- [ ] export database, deleting opted out users
- [ ] deploy database to new site
- [ ] tweak app configuration on new site (e.g. STAGING=0 etc.)
- [ ] DNS configuration
- [ ] SMTP setup on new server
- [ ] email configuration (e.g. routing/management of *@hassleme.co.uk)
- [ ] transfer github repo to hassleme org
- [ ] mySociety comms
